### ISSUE TITLE
Admin Messages.lua

### ISSUE THREAD

**Issue by mxwk** [Chalwk77/HALO-SCRIPT-PROJECTS#129]
**Describe the bug**

The script was not working until I deleted "i ~= p and " on line 66 and I found an error in line 37, it should be "rcon" instead of "rprint".

**Please complete the following information:**
 - EXTENSION: [e.g. SAPP, PHASOR] = SAPP
 - SAPP VERSION: [e.g. 10.2.1] = 10.2.1
 - Script Version [e.g. 1.0.0, 1.0.1] = "1.11.0.0"

**Additional context**

The script works perfectly now after editing the lines mentioned above. I don't know what the issue on line 66 was. I remembered that the script was working in Velocity-Multi-Mod, so I just compared the code from there and tried to make it the same as this one by deleting "i ~= p and " on line 66, surprisingly it worked 😃 Then on line 37 it was a mistype since in the configuration it says that to change the environment you should choose between "chat" and "rcon", this one was fairly simple as I know some coding.

Thanks!

**Comment by Chalwk77** [comment]
I have reviewed the issues described. Good spotting on the typo.
However, the code you removed on line 66: 

```lua
if (i ~= p and player_present(i)) then
```

... was not put there by mistake. This line prevents the newly joined Admin from seeing the join message themselves (by design).
Anyone who is NOT the admin will see it.

**Comment by mxwk** [comment]
Ohhh so the script was working, I just didn't see it lol

I see, thanks for letting me know xD

**Comment by Chalwk77** [comment]
@mxwk

This script has been refactored for you.

You can see all the changes [here](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/commit/6eea10664d4829209f6bdfe3fdb7a32e8860250e).

[Click to view the whole script.](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/UTILITY%20MODS/Admin%20Messages.lua)

New settings:

```lua
local Join_Messages = {

    -- Level 1:
    --
    [1] = "[TRIAL-MOD] %name% joined the server. Everybody hide!",

    -- Level 2:
    --
    [2] = "[MODERATOR] %name% ust showed up. Hold my beer!",

    -- Level 3:
    --
    [3] = "[ADMIN] %name% just joined. Hide your bananas!",

    -- Level 4:
    --
    [4] = "[SENIOR-ADMIN] %name% joined the server.",

    -- Where should messages appear, chat or rcon?
    --
    environment = "chat",

    -- Message alignment (has not affect for clients running Chimera)
    -- Left = |l, Right = |r, Center = |c, Tab: |t
    --
    alignment = "|l",

    --

    -- Advanced users only:
    --
    -- A message relay function temporarily removes the server prefix
    -- and will restore it to this when the relay is finished:
    -- Technical note: This only applies to the chat environment.
    server_prefix = "**SAPP**",
    --
}
-- config ends --
```

**Comment by mxwk** [comment]
Awesome bro! 😃
