### ISSUE TITLE
Anti-aimbot

### ISSUE THREAD

**Issue by oldpowerz** [Chalwk77/HALO-SCRIPT-PROJECTS#133]
- [ ] To mark your selection, put an 'x' between the brackets: [x]

### Will the script be for Halo PC, CE or BOTH?
* [ ] Halo PC
* [X] Halo Custom Edition
* [ ] Both (cross compatibility)

### What server extension are you using?
* [X] SAPP
  * ##### What version of SAPP are you using?
    * [X] 10.1
    * [ ] 10.0
    * [ ] 9.8.1
    * [ ] Earlier version?
    * [ ] Unsure
  
   <sub>You can get this information from your sapp.log file.
   When SAPP loads it will create an entry into this file with a line that looks like this:
   2017-05-25 12:30:0 LOAD SAPP was loaded, Version 10.0 CE</sub>

* [ ] PHASOR
  * ##### What version of PHASOR are you using?
    * [ ] 2.0+ (latest)
    * [ ] 10059
    * [ ] 10058
    * [ ] 10057
    * [ ] Unsure

### Will the script be run on a custom map? (non stock)
* [ ] Yes
* [ ] No
* [X] Unsure

### Will the script need to be map and/or gametype specific?
* [ ] Yes
* [ ] No
* [X] Unsure

## Script Details:
It would be an anti-aimbot since he has sapp, something similar to what is in phasor is not good.
I know it is better to do it manually, there is nothing better than that but you cannot always be one to go around banning those who have aimbot or some other hack

**Comment by Chalwk77** [comment]
This is not a project that I am willing to take on at this time. But you can make a script request on Open Carnage.

Click [here](https://opencarnage.net/index.php?/forum/60-sapp-script-requests/) to go to the script request page.
