### ISSUE TITLE
Portal Gun Improvements

### ISSUE THREAD

**Issue by mxwk** [Chalwk77/HALO-SCRIPT-PROJECTS#135]
Hey Chalwk!

How are you bro? Just thought of some improvements you could do to the portal gun script, it is one of the most fun scripts one that I usually load on my server.

The suggestions are:

1. Allowing admins to change the Portalgun state on/off for players.
2. Making it so that only when one crouches and shoots he/she teleports.
3. Toggle between having to launch the script or having it load automatically in the server like when someone joins then crouches and shoots, he teleports without anyone having to run any commands.

This is for SAPP PC/CE

Thanks!

**Comment by Chalwk77** [comment]
Done.

**Comment by Chalwk77** [comment]
Done.

There are now two versions of Portal Gun.

[Type 1 (link)](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/ATTRACTIVE%20MODS/Portal%20Gun%20(type%201).lua)
> NOTE: In this version, you can portal-gun while in a vehicle. Players do not need to crouch to teleport.

[Type 2 (link)](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/ATTRACTIVE%20MODS/Portal%20Gun%20(type%202).lua)
> NOTE: In this version, you can only portal-gun while walking. Players need to crouch & fire to teleport.

**Comment by mxwk** [comment]
Awesome! Thanks bro!
