### ISSUE TITLE
[FEATURE] Mapcycle Manager Quality Improves

### ISSUE THREAD

**Issue by xdedeone** [Chalwk77/HALO-SCRIPT-PROJECTS#151]
### 🎮 Target Game

- [ ] Halo PC (retail)
- [X] Halo Custom Edition (CE)
- [ ] Both (cross-compatibility)

### 🛠️ Server Extension

- [X] SAPP
- [ ] PHASOR

### 🗺️ Custom Map Usage

- [X] Yes 👍
- [ ] No ❌
- [ ] Unsure ❓

### 🎯 Gametype Specificity

- [X] Yes 👍
- [ ] No ❌
- [ ] Unsure ❓

### 📝 Feature Details

I want some improves to be aplicated to Mapcycle Manager script

1. Script Commands to manage script mapcycle

- /next : Command to skip to next map on mapcycle
- /prev : Command to skip to previus map on mapcycle
- /begin : Command to restart mapcycle an start on first map
- /restart : Command to restart current map
- /map : Command to setup specific map and gametype (like sv_map stock command)

2. Option to sort randomly defined mapcycles by boolean

This option is specific focused on some mapcycles setups.
With many custom maps, or many diferent gametypes, its a good idea setup mapcycle randomly for a fresh and no an specific order for maps/gametypes, so maybe can configure random sort based on specific mapcycle. Like:

- custom_sort = true
- classic_sort = false
- small_sort = true
- ctf_sort = true
- medium_sort = false

### 📈 Potential Impact

- A new and fresh game experience, for no lineal and boring classic mapcycle.
- Good potential for allow multiple servers experience in just 1 server. For example setup so many mapcycles like /race, /ctf, /mixed_maps, /mixed_gametypes, /small_custom_maps, /small_classic_maps etc.
- Great for clan sessions, to easily setup custom games, classic games or scrim games

**Comment by Chalwk77** [comment]
Done. Let me know if there's anything else I can do to help.

### [Click to see the latest update](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/releases/tag/MapcycleManager)
