### ISSUE TITLE
[BUG] Crash Player

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#39]
EventCallback >> OnPlayerPrejoin >> Lua Error: [string "CrashPlayer"]:120: attempt to perform arithmetic on global 'ce' (a nil value)

This error occurs when I place a Hash in HashList, load the script and enter a player.

Note: I'm sorry if you do not explain me correctly.

EXTENSION: SAPP

SAPP VERSION: 10.2.1

Script version: the current version

**Comment by Dark3211** [comment]
many thanks!

**Comment by Dark3211** [comment]
@Chalwk77 many thanks!

**Comment by Chalwk77** [comment]
@Dark3211 No problem (:
Closing this ticket. Feel free to reopen this one or a new one if you experience further issues.

**Comment by Dark3211** [comment]
@Chalwk77 
Hi! One question, is it possible to block by ip?

**Comment by Chalwk77** [comment]
If you want to block an IP I recommend using SAPP's built-in IP Ban command.
The command Syntax is: ipban <player expression> <minutes> <reason>.

Does this help?

**Comment by Dark3211** [comment]
I'm sorry, I did not explain. It would be the player's crash game by ip

**Comment by Chalwk77** [comment]
OKAY, no problem.
I have released Version 2 which does IP comparisons instead of name-to-hash comparisons. Download this version:

https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/UTILITY%20MODS/Crash%20Playe%202.0.lua

**Comment by Dark3211** [comment]
Thank you so much!

**Comment by Chalwk77** [comment]
You're welcome. 
Just a heads up.... I have updated that Lua script once again with some important changes that I forgot about.
