### ISSUE TITLE
Upgrade System (attractive mod) for HPC|CE

### ISSUE THREAD

**Issue by Chalwk77** [Chalwk77/HALO-SCRIPT-PROJECTS#40]
# Upgrade System
Earn 'money' for:

- Kills & Assists
- Kill-Combos & Kill-Streaks
- CTF Scoring
> Use your money to buy weapons and upgrades with custom commands.
> Progress:
> ![Alt text](http://progressed.io/bar/100?title=progress)
### [link to mod](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/ATTRACTIVE%20MODS/Upgrade%20System.lua) | [Project Tracker](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/projects/3)
- - - -

**Comment by Dark3211** [comment]
Dude

Will it work if I add the "god" custom command and can buy 30 seconds?
(the "god" will be over after spending 30 seconds?)



Example

{ ["god2"] = { 'god', "100", "30", "Purchased (30 Seconds of God) for $%price%. New balance: $%balance%", -1 } },

**Comment by Chalwk77** [comment]
> Dude
> 
> Will it work if I add the "god" custom command and can buy 30 seconds?
> (the "god" will be over after spending 30 seconds?)
> 
> Example
> 
> { ["god2"] = { 'god', "100", "30", "Purchased (30 Seconds of God) for $%price%. New balance: $%balance%", -1 } },

Sorry for the late response. 
I have added that feature in the latest udpate.

**Comment by Dark3211** [comment]
@Chalwk77 Cool, thanks

**Comment by Chalwk77** [comment]
No worries. Just a heads up: This mod is still in development, which is why it's in the INDEV directory.
When it's finished, it will be moved to SAPP >> ATTRACTIVE MODS.

**Comment by Dark3211** [comment]
@Chalwk77 If I know, I am testing it if I find an error I will report it, but I think it would be better to give 5 or 10 of money for each kill.

Note: It is only my opinion.

**Comment by Chalwk77** [comment]
[new update] - > Upgrade System.
[!] A couple of bug fixes.
[+] Added stock weapons to the weapons table and options to enable/disable each one individually.
[+] Added stock grenades (Plasma / Frags) to grenade table + options to enable/disable each one.

**Comment by Dark3211** [comment]
the version released 22h ago, has a bug when the game ends and starts another on another map the script stops working, in the version released recently was this bug fixed?

**Comment by Dark3211** [comment]
Script: V2.0
Error:
stack traceback: [string "UpgradeSystem2.0"]:1252: in function <[string "UpgradeSystem2.0"]:1251> [C]: in function '__sub' [string "UpgradeSystem2.0"]:778: in function 'update' [string "UpgradeSystem2.0"]:1044: in function <[string "UpgradeSystem2.0"]:974> EventCallback >> OnPlayerKill >> Lua Error: [string "UpgradeSystem2.0"]:778: attempt to perform arithmetic on local 'balance' (a nil value)

**Comment by Chalwk77** [comment]
Fixed. 

CHANGES:
[+] NEW COMMAND: 
> Command Syntax: /weapons
Weapons table has been updated.

Output Format: (only shows weapons that the current map supports) - which is very intuitive.
>/gold | $200   /brifle | $50   /pistol | $10   /sniper | $15   /pcannon | $35
>/rlauncher | $35   /ppistol | $5   /prifle | $5   /arifle | $7   /fthrower | $7
>/needler | $5   /shotgun | $10

The new /weapons command iterates through the entire weapons table and retrieves the command id, price and weapon tags automatically.

Command Entries are split into 5 columns automatically and rows are determined by the amount of entries, so it's neat and tidy.

New config options:
`local weapon_list = "weapons"`
`local weapon_list_perm = -1`
`local max_columns, max_results = 5, 15`
`local startIndex = 1` -- <<--- do not touch
`local endIndex = max_columns` -- <<--- do not touch
`local spaces = 2 -- Spaces between results`
`local output_format = "/%command% | $%price%"`

**Comment by Dark3211** [comment]
Cool. I have a request, (if possible). I could do a new version without: Combo, Streaks and Assists. And get points for kill.

modify this:
[1] = { "5", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [2] = { "10", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [3] = { "20", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [4] = { "30", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [5] = { "40", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [6] = { "50", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [7] = { "60", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [8] = { "70", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [9] = { "80", "10", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [10] = { "90", "20", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },

        [11] = { "100", "30", "Kills: (%kills%) +%upgrade_points% Upgrade Points" },


    },


to this:

kill = {

[1] = { "10", "KILL (+%upgrade_points% points)" },

},
(if it is possible)

**Comment by Chalwk77** [comment]
# ADDED
```lua
    -- Every kill will reward X amount of points.
    on_kill = {
        -- POINTS | MESSAGE
        enabled = true, -- Set to 'false' to disable
        {"10", "Kill (+%upgrade_points% Upgrade Points)"}
    },
```

You can now enable or disable the `combos, streaks, assists and kills tables`.

**Comment by Dark3211** [comment]
*Bug*

Error:

stack traceback: [string "UpgradeSystem2.0"]:1383: in function <[string "UpgradeSystem2.0"]:1382> [C]: in function '__add' [string "UpgradeSystem2.0"]:902: in function 'update' [string "UpgradeSystem2.0"]:575: in function 'AddRemove' [string "UpgradeSystem2.0"]:617: in function <[string "us"]:450> LuaEventCallback >> OnServerCommand >> Lua Error: [string "UpgradeSystem2.0"]:902: attempt to perform arithmetic on a nil value -------------------------------------------------------- Please report this error on github: https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/issues --------------------------------------------------------

**Comment by Dark3211** [comment]
*Bug*

He does not let me buy frag grenades/plasma grenades, he says "That does not command work on this map." Test map: "BloodGulch" and "RatRace"

**Comment by Dark3211** [comment]
[Bug]

Error:

stack traceback: [string "UpgradeSystem2.0"]:1383: in function <[string "UpgradeSystem2.0"]:1382> [C]: in function '__sub' [string "UpgradeSystem2.0"]:904: in function 'update' [string "UpgradeSystem2.0"]:1160: in function <[string "UpgradeSystem2.0"]:1088> EventCallback >> OnPlayerKill >> Lua Error: [string "UpgradeSystem2.0"]:904: attempt to perform arithmetic on local 'balance' (a nil value)

**Comment by Chalwk77** [comment]
# BUG FIXES:
* Frag/Plasma grenade assignment fixed.
* Betray will now deduct money from the killer instead of the victim.
* Another fix for the Column sorting routines for "/weapons" command.

**Comment by Dark3211** [comment]
Ok, (HCE) Server name: "! ROCKTS »BLOODGULCH«"

the purchase of "weapons" does not work on my server. the gametype is not "all weapons"

**Comment by Chalwk77** [comment]
You can enable and disable each individual weapon in the weapons table.
Set "true" to "false" to disable them and only leave index 4 (rocket launcher) enabled.

**Comment by Dark3211** [comment]
I know, I have most of the weapons disabled

**Comment by Chalwk77** [comment]
Are OK. I made a video demonstrating how to do this in case you didn't know.
https://www.youtube.com/watch?v=XHtC-Cs3tgA&feature=youtu.be

**Comment by Dark3211** [comment]
Script Version: 1.26

this error was fixed in version 1.35?

stack traceback: [string "UpgradeSystem"]:1390: in function <[string "UpgradeSystem"]:1389> [C]: at 0x011d6090 [C]: in function 'update' [string "UpgradeSystem"]:1175: in function <[string "UpgradeSystem"]:1092> EventCallback >> OnPlayerKill >> Lua Error: [string "UpgradeSystem"]:1175: money:update() -> Unable to get "balance".

**Comment by Chalwk77** [comment]
Do you have "save_money" set to TRUE or FALSE?

**Comment by Dark3211** [comment]
false

**Comment by Dark3211** [comment]
My name in the game is: "LilPump" or "_!GoD", I play saturdays and sundays mostly.

**Comment by Dark3211** [comment]
out of curiosity, why did I want to know my name in the game?

**Comment by Chalwk77** [comment]
> [Bug]
> 
> Script Version: 1.26
> 
> this error was fixed in version 1.35?
> 
> stack traceback: [string "UpgradeSystem"]:1390: in function <[string "UpgradeSystem"]:1389> [C]: at 0x011d6090 [C]: in function 'update' [string "UpgradeSystem"]:1175: in function <[string "UpgradeSystem"]:1092> EventCallback >> OnPlayerKill >> Lua Error: [string "UpgradeSystem"]:1175: money:update() -> Unable to get "balance".

### FIXED.
### Updated to version 1.42

**Comment by Dark3211** [comment]
I tried version 1.46 and it does not give errors in the console, however when doing many kills it does not give me the points.

(After about 20 kills)

**Comment by Dark3211** [comment]
I found these errors.

Bugs:

stack traceback: [string "UpgradeSystem"]:1504: in function <[string "UpgradeSystem"]:1503> [C]: at 0x011d6090 [C]: in function 'update' [string "UpgradeSystem"]:1283: in function <[string "UpgradeSystem"]:1201> EventCallback >> OnPlayerKill >> Lua Error: [string "UpgradeSystem"]:1283: money:update() -> Unable to get "balance". -------------------------------------------------------- Please report this error on github: https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/issues Script Version: 1.46 -------------------------------------------------------- stack traceback: [string "UpgradeSystem"]:1504: in function <[string "UpgradeSystem"]:1503> [C]: at 0x011d6090 [C]: in function 'update' [string "UpgradeSystem"]:1272: in function <[string "UpgradeSystem"]:1201> EventCallback >> OnPlayerKill >> Lua Error: [string "UpgradeSystem"]:1272: money:update() -> Unable to get "balance". -----------------------------------------------,--------- Please report this error on github: https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/issues Script Version: 1.46 --------------------------------------------------------

**Comment by Chalwk77** [comment]
I was unable to reproduce the same error, as such, it's very difficult to ascertain the circumstances under which are causing this problem. I have made some changes in hopes that it will fix the issue but there are no guarantees at this point. Script version is now 1.47.

**Comment by Dark3211** [comment]
Ok I understand, if this helps, I have all the weapons disabled and also combos, streaks, assists and "total deaths"

**Comment by Chalwk77** [comment]
Let me know if you continue to have the same problem.

**Comment by Dark3211** [comment]
Well, at the moment the server is full and has not presented any errors.

**Comment by Chalwk77** [comment]
Thank you to everybody who helped test and find errors this.
@RoadHog, @Dark3211, @VicFirth, @iAirPirate, @TheManyRandomPlayers

**Comment by Dark3211** [comment]
@Chalwk77 The players that enter my server and some of my clan informed me that the money does not work correctly, (they say that almost nobody passes the 100 points), the console does not present any error. My question is, what can I do to prevent this from happening?

**Comment by Chalwk77** [comment]
Something to note:
If 'save_money' is disabled, player points are reset to 0 (by design) when they quit.
When they rejoin the server and discover their points are gone, this is why.

Change: `local starting_balance = 0` (on or near line 34), to suit your needs.

Beyond that, I can only recommend changing the points received for kills, etc.
Everything is working fine for me.
