### ISSUE TITLE
Dropped Weapon Deleter

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#42]
Script For: Halo CE/PC

Extension: SAPP

SAPP Version: 10.2.1

Script Run On Custom Maps: Yes

Will the script need to be map and/or gametype specific? No

Details

(delete when dying and leave the server).

Choose Remove Pomegranates.

Do not Remove flag/oddball in ctf.

For his do not explain correctly here a script with my specifications: 

https://opencarnage.net/applications/core/interface/file/attachment.php?id=302

I stopped using it because after the players entered and left the server it gave an error.

To avoid creating a new script could you update this?

Error:

EventCallback >> OnTick >> Lua Error: [string "dropweapondeleted"]:71: attempt to perform arithmetic on local 'metaid' (a nil value)

(Removes the weapon from the live players) 

Thanks in advance!!.

**Comment by Chalwk77** [comment]
Alright. I have taken a quick look at this script and although I couldn't reproduce the error you experienced, I have added a nil-check which should prevent the script from throwing the aforementioned error.

Here is the updated script: https://pastebin.com/jS9KXvUi
Note: This link is set to expire in 24 hours.

**Comment by Dark3211** [comment]
Thank you!
