### ISSUE TITLE
Player Vanish Script 

### ISSUE THREAD

**Issue by Sinisterhpc** [Chalwk77/HALO-SCRIPT-PROJECTS#48]
- [x] To mark your selection, put an 'x' between the brackets: [x]

### Will the script be for Halo PC, CE or BOTH?
* [ ] Halo PC
* [ ] Halo Custom Edition
* [x] Both (cross compatibility)

### What server extension are you using?
* [x] SAPP
  * ##### What version of SAPP are you using?
    * [x] 10.2.1
    * [ ] 10.1
    * [ ] 10.0
    * [ ] 9.8.1
    * [ ] Earlier version?
    * [ ] Unsure
  
   <sub>You can get this information from your sapp.log file.
   When SAPP loads it will create an entry into this file with a line that looks like this:
   2017-05-25 12:30:0 LOAD SAPP was loaded, Version 10.0 CE</sub>

* [ ] PHASOR
  * ##### What version of PHASOR are you using?
    * [ ] 2.0+ (latest)
    * [ ] 10059
    * [ ] 10058
    * [ ] 10057
    * [ ] Unsure

### Will the script be run on a custom map? (non stock)
* [x] Yes
* [ ] No
* [ ] Unsure

### Will the script need to be map and/or gametype specific?
* [ ] Yes
* [x] No
* [ ] Unsure

## Script Details:
* Please be as descriptive as possible so I know how to help you.

write your description here...

Hello, basically, what this script does, is vanishes the player who enable it with a command while scrim_mode on, other players cannot see the player but the player can kill normally, and it can also boost the player where he aims at, I'm really interested in a script like that, it already exists but I'm not sure who is his creator, I've played scrims recently and the player who has it has used it and it's impossible to kill him, it would be really great if you could create it, please, I've also got a fragment of screenshot of the script, hope it helps as reference of the original script.

![script](https://user-images.githubusercontent.com/46983623/58144680-9acba580-7c0c-11e9-9037-d5b57cbe40c2.png)

Thank you so much.

**Comment by Chalwk77** [comment]
Sure thing. I'll see what I can come up with.

**Comment by Sinisterhpc** [comment]
Thank you so much, I really appreaciate it!

**Comment by Chalwk77** [comment]
Alright, here you go.
## [link to mod](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/ATTRACTIVE%20MODS/Player%20Vanish.lua)

If you discover any bugs or wany anything changed, let me know (:

**Comment by Sinisterhpc** [comment]
Omg, this is a really awesome work!, it works pretty cool, thank you so much!

btw I have found some things while using it, one of them is the scrim_mode on, but you've answered that already, also when changing map and gametype it stops working, I need to use /reload command so it works again, is there any reason causing that?, other than that, it works pretty awesome, I'm really happy about this script, you're a master.

Here's a video: https://youtu.be/0FEAV8BXWwQ

**Comment by Chalwk77** [comment]
Cool man! Glad you like it.
The script has been updated (and tested).

#### New setting:
* vanish.auto_off
> Toggle this setting on or off with 'true' or 'false'.

If this is true, vanish will be auto-disabled (for all players) when the game ends, thus, players will not be in vanish when the next game begins.

**Comment by Sinisterhpc** [comment]
Wow, this is just fantastic, I'm so happy with this script, it works great now.

**Comment by Sinisterhpc** [comment]
Wow, this is just fantastic, I'm so happy with this script, it's working great now.

Here's a video I recorded: https://youtu.be/liyrcVUS7Oo

You're really great at your projects, I'm really thankful to you for making this possible, big shout-out to you and your work.

**Comment by Chalwk77** [comment]
@Sinisterhpc 
No worries! I am closing this ticket now, but if you need to report any bugs or want something changed, feel free to reopen it.

**Comment by Chalwk77** [comment]
@Sinisterhpc 
I have updated this mod with a new feature and bug fix:

### vanish.hide_vehicles
> If this is enabled, your vehicle will disappear too!

### BUGFIX:
> Vanished players will now disappear from the radar.

**Comment by Sinisterhpc** [comment]
That's the touch that made this script perfect!

It's working so great!  https://youtu.be/3QDT36Rw9N0

btw, I do have a question, when I use the vanish command the server prefix changes to **SERVER**, it can be customized? like instead of changing it to **SERVER**, it can change to ** Admin **, so the messages have a space between the prefix and the text, for example:

How it looks currently:
**SERVER**You're playing on X server.

How it would look:
** Admin ** You're playing on X server.

Thank you!

**Comment by Chalwk77** [comment]
Hello.

I have made a few improvements.
### All changes can be seen here: [changes](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/commit/303318da765a7cae08afc6766d2ed7a4e179777d)

* New setting: `vanish.camouflage`
> If this is true, you will be camouflaged.
Despite the fact that players won't be able to see you anyway, this feature doubles
as a visual reminder to the player that they have vanished.

* This script will now kill the vanished player silently (no death penalty + instant respawn) and reset a few parameters.

> You will teleport to your previous location when you respawn.
> If you were in a vehicle when Vanish was disabled, you will be inserted back into that exact same vehicle (in the same seat).

* Vanish status is now saved to a temp file called 'vanish.tmp', located in 'server root/sapp/vanish.tmp'.

**Comment by Sinisterhpc** [comment]
Hello! this is so awesome!

I've tested it and it's working great so far, I'm really happy with this update. Thank you so much for all the work you done on this script, I'll let you know if there any bugs or additional features want to be added.

Only a question, this script has god mode, when I use it, I stay in front of a warthog and my friend can still kill me with it, do I need to enable that function?

**Comment by Chalwk77** [comment]
> Edit: I tested it again, and it seems to be working great now. Thank you so much!

Awesome man!

**Comment by Chalwk77** [comment]
I wasn't planning on updating this mod again, but someone else pointed out a bug, which I have fixed in the latest updated (v1.5). I also took the opportunity to make some documentation edits (see changelog at the bottom of the script), and also added a new setting.

New setting: `vanish.hide_from_radar` -> If this is true, you will be hidden from radar.

**Comment by Sinisterhpc** [comment]
This script is working great for me, it's awesome! I'll let you know if there are any bugs, or any features want to be added.

Thank you so much!
