### ISSUE TITLE
Admin Messages
(Admin Join Messages)

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#52]
[Update]
(Where to Show The Message)

Example:
"Message Alignment"

alignment = "c" -- Left = l,    Right = r,    Center = c,    Tab: t

it's possible?

**Comment by Chalwk77** [comment]
Updated (:
https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/UTILITY%20MODS/Admin%20Messages.lua

**Comment by Dark3211** [comment]
Thx!
