### ISSUE TITLE
Team Balance

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#53]
Script For: Halo CE/PC

Extension: SAPP

SAPP Version: 10.2.1

Script Run On Custom Maps: Yes

Will the script need to be map and/or gametype specific? No

Details

(Team Balance)

The error is reproduced when the equipment balance is made.

This is the script:

https://opencarnage.net/index.php?/topic/3761-team-autobalance/

To avoid creating a new script could you update this?

Error:

LuaTimer >> SwitchPlayerIfPossible >> Lua Error: [string "team_balance"]:56: attempt to concatenate local 'smaller_team' (a nil value)

Thanks in advance!!.

**Comment by Chalwk77** [comment]
Hello. 
Here is the edited (working) script: https://pastebin.com/L31MPCme
Note: This link expires in 1 week.

**Comment by Dark3211** [comment]
Thanks!

**Comment by Dark3211** [comment]
Hi, I have a doubt Is it possible to detect the Phantom Shot? (Test the Devieth script but it doesn't detect them correctly)

**Comment by Dark3211** [comment]
@Chalwk77

Hello!

I have a doubt Is it possible to detect the Phantom Shot?

(Test the Devieth script but it doesn't detect them correctly)
