### ISSUE TITLE
upgrade_system 

### ISSUE THREAD

**Issue by ChipProgrammer** [Chalwk77/HALO-SCRIPT-PROJECTS#54]
stack traceback:
        [string "upgrade_system"]:1540: in function <[string "upgrade_system"]:1539>
        [C]: at 0x71bc5310
        [C]: in function 'getbalance'
        [string "upgrade_system"]:1041: in function 'update'
        [string "upgrade_system"]:1307: in function <[string "u
EventCallback >> OnPlayerKill >> Lua Error: [string "upgrade_system"]:1041: money:getbalance() -> Something went wrong!
--------------------------------------------------------
Please report this error on github:
https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/issues
Script Version: 1.47
--------------------------------------------------------

**Comment by ChipProgrammer** [comment]
This other one showed ~30 minutes ago:

stack traceback:
        [string "upgrade_system"]:1540: in function <[string "upgrade_system"]:1539>
        [C]: at 0x71bc5310
        [C]: in function 'ipairs'
        [string "upgrade_system"]:1425: in function 'getIP'
        [string "upgrade_system"]:1229: in function <[string "upgrad
EventCallback >> OnPlayerDisconnect >> Lua Error: [string "upgrade_system"]:1425: bad argument #1 to 'ipairs' (table expected, got nil)

**Comment by Chalwk77** [comment]
Wow. I completely forgot about this. I'll take a look today.

**Comment by ChipProgrammer** [comment]
https://app.box.com/s/9ujn1aonhndvqqss4nrr3rqkht29cny4
Hopefully, you can download the latest copy that I have modified to fix some issues.

**Comment by Chalwk77** [comment]
@ChipProgrammer [Refer to this](#53)

**Comment by Chalwk77** [comment]
@ChipProgrammer 

This script was rewritten from scratch yesterday.

[DOWNLOAD PAGE](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/ATTRACTIVE%20MODS/Market.lua)
