### ISSUE TITLE
Replace Weapon Projectile

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#55]
Script For: Halo CE/PC

Extension: SAPP

SAPP Version: 10.2.1

Script Run On Custom Maps: Yes

Will the script need to be map and/or gametype specific? No

 Details:

(Replace Weapon Projectile)
 Examples:

Sniper fires Tank shells

Gun fires Sniper shells

Shotgun fires Rocket Launcher shells

Among others..

(If possible)
to be able to change the shells of each weapon.

(I hope it is possible to create this script)

Thanks!!

**Comment by Chalwk77** [comment]
Completed
### [link to mod](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/ATTRACTIVE%20MODS/Replace%20Weapon%20Projectile.lua)

#### NOTE: The replacement projectile will still appear as the original projectile (but function properly).

#### If you want to be able to see replacement projectiles, let me know.
#### It's quite an involved process.

**Comment by Dark3211** [comment]
Like this is ok, Thanks!!

**Comment by Dark3211** [comment]
Could you add the grenade projectile change?

**Comment by Dark3211** [comment]
@Chalwk77 Could you add the grenade projectile change?

**Comment by Chalwk77** [comment]
> _Note_
> If you do the "see replacement projectiles", would this not crash on custom maps?

No. This script will not crash your server. Projectiles using non-stock tag ids will need to be added to the projectiles table manually.

**Comment by Chalwk77** [comment]
> _Note_
> If you do the "see replacement projectiles", would this not crash on custom maps?

No. This script will not crash your server. However, projectiles with non-stock tag ids (custom tag ids) will need to be added to the projectiles table manually (one by one) in order to change the respective weapon.

To actually "see" the replacement weapon projectiles, I have to write some object Dependency Swapping logic which is very time consuming and rather a pain but doable. I actually do this in my Snipers Dream Team mod which is in Miscellaneous directory.

**Comment by Chalwk77** [comment]
Mod updated.

Added: Grenades + Damage Multipliers
Changed: Tag lookup function

**Comment by Dark3211** [comment]
@Chalwk77 Oh, I thought that "seeing replacement projectiles" would crash. 


Thanks for the explanation!

**Comment by Dark3211** [comment]
@Chalwk77 **I would like to "see the projectile replacement". I will wait for the time that be necessary.**   :v

**Comment by Dark3211** [comment]
Is it possible to add projectile speed change?
