### ISSUE TITLE
script

### ISSUE THREAD

**Issue by El-Karma** [Chalwk77/HALO-SCRIPT-PROJECTS#75]
- [ ] To mark your selection, put an 'x' between the brackets: [x]

### Will the script be for Halo PC, CE or BOTH?
* [ ] Halo PC
* [x ] Halo Custom Edition
* [ ] Both (cross compatibility)

### What server extension are you using?
* [x] SAPP
  * ##### What version of SAPP are you using?
    * [x ] 10.2.1
    * [ ] 10.0
    * [ ] 9.8.1
    * [ ] Earlier version?
    * [ ] Unsure
  
   <sub>You can get this information from your sapp.log file.
   When SAPP loads it will create an entry into this file with a line that looks like this:
   2017-05-25 12:30:0 LOAD SAPP was loaded, Version 10.0 CE</sub>

* [ ] PHASOR
  * ##### What version of PHASOR are you using?
    * [ ] 2.0+ (latest)
    * [ ] 10059
    * [ ] 10058
    * [ ] 10057
    * [ x] Unsure

### Will the script be run on a custom map? (non stock)
* [ x] Yes
* [ ] No
* [ ] Unsure

### Will the script need to be map and/or gametype specific?
* [ ] Yes
* [x ] No
* [ ] Unsure

## Script Details:
* Please be as descriptive as possible so I know how to help you.

write your description here...Hello! I need to know if they can create spartan afks bots for sapp servers in halo ce..thanks !!
![haloce 2019](https://user-images.githubusercontent.com/57968024/69195821-60c35980-0af2-11ea-98af-09ef2f342632.jpg)

**Comment by Chalwk77** [comment]
Are you referring to afk `(AI Bots)` with names that appear in the scoreboard?
This is not possible, unfortunately.

However, there are two things you or I can do.
You could use the Generic Halo MultiClient to add `"bots"` to the server or I could write a script that spawns `Cyborgs` (spartan biped with no ai) - they won't have names that appear in the scoreboard though.

**Comment by El-Karma** [comment]
62/5000
If it seems perfect, tell me the steps to follow or what do we do?

________________________________
De: Jericho <notifications@github.com>
Enviado: martes, 19 de noviembre de 2019 05:40 p. m.
Para: Chalwk77/HALO-SCRIPT-PROJECTS <HALO-SCRIPT-PROJECTS@noreply.github.com>
CC: El-Karma <cruzazul_clan@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Chalwk77/HALO-SCRIPT-PROJECTS] script (#75)


Are you referring to afk (AI Bots) with names that appear in the scoreboard?
This is not possible, unfortunately.

However, there are two things you or I can do.
You could use the Generic Halo MultiClient to add "bots" to the server or I could write a script that spawns Cyborgs (spartan biped with no ai) - they won't have names that appear in the scoreboard though.

**Comment by Chalwk77** [comment]
Follow this Tutorial for the Halo Generic MultiClient:
https://www.youtube.com/watch?v=jz4Td_yJ2wg
