### ISSUE TITLE
Uber (v1.2)

### ISSUE THREAD

**Issue by Chalwk77** [Chalwk77/HALO-SCRIPT-PROJECTS#79]
# Uber (Attractive Mod)

#### Description: Inject yourself into a teammate's vehicle by typing "uber" or crouching.
This script will scan all available vehicles that are occupied by teammates.
The first scan checks available gunner seats. If one is available, you will enter into it.
If no gunner seats are available, the script will then scan for available passenger seats and insert you into one. If neither gunner or passenger seats are vacant the script will send you an error.

Features:
* Customizable activation keywords: i,e "uber", "taxi", "cab"
* Limit uber calls per game (20 by default)
* Crouch to call an uber (on by default)
* Auto Ejector: Vehicle occupants without a driver will be ejected after X seconds (on by default)
* Cooldowns (you have to wait 10 seconds before attempting to call an uber) - on by default
* Works on most custom maps
* Compatible with any team-based game type (incl CTF, Oddball)
* Customizable messages
* Option to prevent players holding the objective from calling an uber (applies to CTF and Oddball)

**Comment by HLN-Se7en** [comment]
**Thanks man great job and great script.**

**Comment by Chalwk77** [comment]
Updated to version 1.2 with bug fixes and a few other improvements.

**Comment by Chalwk77** [comment]
Download Link fixed in the OP.
