### ISSUE TITLE
Team color changer color voting

### ISSUE THREAD

**Issue by denngray** [Chalwk77/HALO-SCRIPT-PROJECTS#80]
- [ ] To mark your selection, put an 'x' between the brackets: [x]

### Will the script be for Halo PC, CE or BOTH?
* [ ] Halo PC
* [ ] Halo Custom Edition
* [x] Both (cross compatibility)

### What server extension are you using?
* [ x] SAPP
  * ##### What version of SAPP are you using?
    * [ ] 10.1
    * [ ] 10.0
    * [x] 9.8.1
    * [ ] Earlier version?
    * [ ] Unsure
  
   <sub>You can get this information from your sapp.log file.
   When SAPP loads it will create an entry into this file with a line that looks like this:
   2017-05-25 12:30:0 LOAD SAPP was loaded, Version 10.0 CE</sub>

* [ ] PHASOR
  * ##### What version of PHASOR are you using?
    * [ ] 2.0+ (latest)
    * [ ] 10059
    * [ ] 10058
    * [ ] 10057
    * [ ] Unsure

### Will the script be run on a custom map? (non stock)
* [ ] Yes
* [x] No
* [ ] Unsure

### Will the script need to be map and/or gametype specific?
* [ ] Yes
* [x] No
* [ ] Unsure

## Script Details:
* Please be as descriptive as possible so I know how to help you.

write your description here...
I have a team color changer I use on dangercanyon, would like players to vote on team colors for next game i.e.
1-purple v Cobalt
2-white v black
3-pink v green
Etc...

**Comment by Chalwk77** [comment]
#### Progress Update: 90% complete
> Will post link to mod when finished.

**Comment by Chalwk77** [comment]
#### Hello, Ro@dhog. 
##### This mod has been completed. Sorry about the long delay! I have been busy with other things.

## [download link](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/UTILITY%20MODS/Custom%20Team%20Colors%20(1.0).lua)

**Comment by denngray** [comment]
NP I was in no hurry :) thank you Chalwk

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Chalwk77** [comment]
This mod has been updated (the version is now 1.1)

**Comment by Chalwk77** [comment]
Updated with a small fix in the OnServerCommand() function

**Comment by Chalwk77** [comment]
Updated once again with an important bug fix

**Comment by Chalwk77** [comment]
#### Updated once again with another bug fix

**Comment by denngray** [comment]
I will probably be moving the severs to digital ocean in the next week.
Digital Ocean has a faster infrastructure than VULTR and built in free fire
wall DDOS protection.
When I do I will send you the login information.
I just downloaded the entire server today.

Road

**Comment by Chalwk77** [comment]
Thanks for the heads up RoadHog
