### ISSUE TITLE
Velocity errors

### ISSUE THREAD

**Issue by cyferX** [Chalwk77/HALO-SCRIPT-PROJECTS#81]
**Describe the bug**
nothing happens during the game but stack traceback issue appear in the console
lines 7175 & 7176 string "velocity Multi_mod 
line =s 
![velocity error](https://user-images.githubusercontent.com/63085739/78320872-83ea2500-7538-11ea-8c7e-826b74740fe6.jpg)
6589 in function string velocity multi mod
j 

**To Reproduce**
Steps to reproduce the behaviour:
1. Do this '...'
2. Do that '....'
3. Then this '....'

**Expected behaviour**

**Screenshots**

**Please complete the following information:**
 - EXTENSION: [e.g. SAPP, PHASOR]
 - SAPP VERSION: [e.g. 10.2.1]
 - Script Version [e.g. 1.0.0, 1.0.1]

**Additional context**

**Comment by Chalwk77** [comment]
Thank you, CyferX.
I will look at this when I can.
