### ISSUE TITLE
Vanish [BUG]

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#83]
Bug:

LuaEventCallback >> OnDamageApplication >> Lua Error: [string "vanish"]:1092: attempt to index local 'v' (a nil value)

It is produced:

Occurs when you load the script and activate "vanish mode" on any player.
You can deal damage to enemies while in "vanish mode",
after the victim (the other players) exit and enter the server, it stops happening and the damage is disabled.

 - EXTENSION:  SAPP
 - SAPP VERSION: 10.2.1
 - Script Version: (v 1.0) v1.5?
(in the description it says v1.0 ... but in script_version it says 1.5)

**Comment by Chalwk77** [comment]
Thank you for reporting this bug. I will look into this when able.

**Comment by Chalwk77** [comment]
This mod has been updated for a fix for the 1st bug you mentioned.
The second problem you described should have been resolved as a result of fixing the first issue.
If you still have any issues, please let me know!

Kind Regards,
Chalwk

**Comment by Dark3211** [comment]
It didn't work.
but change/delete parts of script and it seems to work now

what changes:

function OnDamageApplication(PlayerIndex, CauserIndex, MetaID, Damage, HitString, Backtap)
    if (vanish.block_damage) then
        if (tonumber(CauserIndex) > 0 and PlayerIndex ~= CauserIndex) then
            local kip = getip(CauserIndex, true)

            -- 22/04/20 [Fixed nil check error]:
            local k = vanish[kip] or nil
            if (k ~= nil) then
                if (k.enabled) then
                    return false
                end
            end
            --
        end
    end
end

**Comment by Dark3211** [comment]
It didn't work.
but change/delete parts of script and it seems to work now.

changes:

``function OnDamageApplication(PlayerIndex, CauserIndex, MetaID, Damage, HitString, Backtap)

  if (vanish.block_damage) then
     if (tonumber(CauserIndex) > 0 and PlayerIndex ~= CauserIndex) then
        local kip = getip(CauserIndex, true)

        -- 22/04/20 [Fixed nil check error]:
        local k = vanish[kip] or nil
        if (k ~= nil) then
            if (k.enabled) then
                return false
            end
        end
        --
    end
end
end``
