### ISSUE TITLE
Console Log

### ISSUE THREAD

**Issue by Dark3211** [Chalwk77/HALO-SCRIPT-PROJECTS#89]
### Will the script be for Halo PC, CE or BOTH?
* [ ] Halo PC
* [ ] Halo Custom Edition
* [x] Both (cross compatibility)

### What server extension are you using?
* [x] SAPP
  * ##### What version of SAPP are you using?
    * [x] 10.2.1
    * [ ] 10.0
    * [ ] 9.8.1
    * [ ] Earlier version?
    * [ ] Unsure
### Will the script be run on a custom map? (non stock)
* [x] Yes
* [ ] No
* [ ] Unsure

### Will the script need to be map and/or gametype specific?
* [ ] Yes
* [x] No
* [ ] Unsure

## Script Details:

Save a log file (console.log) in the root folder.

Hello, I would like to know if it is possible to create a script that shows everything that is shown in the console (console log).

Example:

sv_name: SAPP V10.2.1
sv_rcon_password: 'password'
true
sv_maxplayers: 16
0
Loading SAPP ...
Starting threads ...
Searching for Halo functions ...
Patching Halo's code for codecaves ...
Loading commands ...
14 custom commands were loaded.
Loading Lua scripts ...
Loading settings ...
- Loading SAPP settings -
SAPP Console: enabled
Map Voting: enabled
Ping kick: 500 ms
AFK kick: 300 s
Message Prefix:
true
Lua: enabled
Anti Glitch: enabled
Scores to ban aimbotter: 5000
Ban Type: IP Ban, Length: 1440 minutes
Votes to skip the map: 55%
No Lead: enabled
Anti Camp is enabled, Time: 10 s, Distance: 14.00 u
SAPP Logging: enabled
Log thread has been started!
Successfully loaded sm.lua!
- Loading SAPP settings finished -
Network thread has been started!
SAPP Version 10.2.1 CE by sehé °°, originally by Termy || halo.isimaginary.com
Successfully loaded sapp.dll!
Minimum level required for SightJacking: 3
sv_name: SAPP V10.2.1
sv_maxplayers: 16
sv_public_value: 1
New Game, Map: wizard, Mode: slayer
External IP Received: 000.000.00.000:2010
 
If possible, show the errors of the scripts that are loaded on the server

Example of Error:

OnScriptUnLoad >> Lua Error:  attempt to call a nil value

**Comment by Chalwk77** [comment]
Unfortunately, it's not possible to display certain start-up information; Which is most of it, actually.
But I'll see what I can come up with.

**Comment by Dark3211** [comment]
Ok, but it is possible to record the errors (shown in the console, if they have any) of all the scripts loaded by the server?

**Comment by Chalwk77** [comment]
Due to a limitation with SAPP, the only thing you can do is copy/paste the below code into each individual script you have. Put this at the bottom of each script.

SAPP's OnError() function is raised every time there is an error but this is on a per-script basis.

```lua
function OnError()
	local path = "sapp//errors.txt"
	local file = assert(io.open(path, "a+"))
	if (file ~= nil) then
		file:write(debug.traceback() .. " \n\n")
		io.close(file)
	end
end
```
